Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -15,45 +15,45 @@ env:
   WERROR: 1
 
 jobs:
-  build-macos:
-    name: macOS XCODE5
-    # See https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source
-    runs-on: macos-14
-    env:
-      JOB_TYPE: BUILD
-      HOMEBREW_NO_INSTALL_CLEANUP: 1
-      HOMEBREW_NO_AUTO_UPDATE: 1
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Install Linux Toolchain
-        run: |
-          brew tap FiloSottile/homebrew-musl-cross
-          brew install musl-cross
-
-      - name: Install Dependencies
-        run: brew install openssl mingw-w64
-
-      - name: CI Bootstrap
-        run: |
-          src=$(/usr/bin/curl -LfsS https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1
-
-      - run: ./build_duet.tool
-      - run: ./build_oc.tool
-
-      - name: Upload to Artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: macOS XCODE5 Artifacts
-          path: Binaries/*.zip
-      - name: Upload to Release
-        if: github.event_name == 'release'
-        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2.9.0
-        with:
-          repo_token: ${{ secrets.GITHUB_TOKEN }}
-          file: Binaries/*.zip
-          tag: ${{ github.ref }}
-          file_glob: true
+#  build-macos:
+#    name: macOS XCODE5
+#    # See https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source
+#    runs-on: macos-14
+#    env:
+#      JOB_TYPE: BUILD
+#      HOMEBREW_NO_INSTALL_CLEANUP: 1
+#      HOMEBREW_NO_AUTO_UPDATE: 1
+#    steps:
+#      - uses: actions/checkout@v4
+#
+#      - name: Install Linux Toolchain
+#        run: |
+#          brew tap FiloSottile/homebrew-musl-cross
+#          brew install musl-cross
+#
+#      - name: Install Dependencies
+#        run: brew install openssl mingw-w64
+#
+#      - name: CI Bootstrap
+#        run: |
+#          src=$(/usr/bin/curl -LfsS https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1
+#
+#      - run: ./build_duet.tool
+#      - run: ./build_oc.tool
+#
+#      - name: Upload to Artifacts
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: macOS XCODE5 Artifacts
+#          path: Binaries/*.zip
+#      - name: Upload to Release
+#        if: github.event_name == 'release'
+#        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd # v2.9.0
+#        with:
+#          repo_token: ${{ secrets.GITHUB_TOKEN }}
+#          file: Binaries/*.zip
+#          tag: ${{ github.ref }}
+#          file_glob: true
 
   build-linux-clangpdb:
     name: Linux CLANGPDB
